-- UPDATE STATEMENTS -- 

-- DECREASES THE USER RATING BY 1 IF THEY HAVENT HAD A TRANSACTION IN 3 MONTHS --

UPDATE u
SET u.Rating = u.Rating - 1
FROM Users u
JOIN UserTransactions ut on (u.UserID = ut.SellerID)
WHERE (Max(ut.TransactionDate) < DATEDIFF(CURDATE(), INTERVAL 3 MONTH))


-- DELETES TOOLS FROM THE UNAVAILABLE LIST IF ITS ALREADY BEEN RETURNED --
DELETE ut.ToolID
FROM UnavailableTools ut
WHERE ut.ReturnDate < CURDATE()

-- IF A TOOLS IS AVAIABLE FOR SALE, NOW IT IS NOT (CAN BE USED TO SHOW THAT THE SITE IS CLOSED FOR MAINTANACE)--
UPDATE Tools t
SET t.ForSale = False
WHERE t.ForSale = True
