-- UPDATE STATEMENTS --

-- DECREASES THE USER RATING BY 1 IF THEY HAVENT HAD A TRANSACTION IN 3 MONTHS --
UPDATE Users u, (
	SELECT
		SellerID
    FROM
		UserTransactions
	GROUP BY
		SellerID
	HAVING
		MAX(TransactionDate) < CURDATE() - INTERVAL 3 MONTH
	) AS ut
SET
	u.Rating = u.Rating - 1
WHERE
	u.UserID = ut.SellerID;


-- DELETES TOOLS FROM THE UNAVAILABLE LIST IF ITS ALREADY BEEN RETURNED --
DELETE FROM UnavailableTools ut
WHERE ut.ReturnDate < CURDATE();

-- IF A TOOLS IS AVAIABLE FOR SALE, NOW IT IS NOT (CAN BE USED TO SHOW THAT THE SITE IS CLOSED FOR MAINTANACE)--
UPDATE Tools t
SET t.ForSale = False
WHERE t.ForSale = True;
